# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Alv
subtitle: Yuste
description: Hello! I'm Alvaro and I love **creating**.
  I achieve it by **coding**, composing **music** and **writing**.
author: Álvaro Yuste
language: en_EN
timezone: Europe/Madrid

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.alvyuste.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: Writing
category_map:
  Writing: Thoughts and everyday dramas
  Coding: Work, resources and tips
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM Mo, YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: cactus-light

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

cv:
  contact:
    who: Álvaro Yuste Torregrosa
    what: Creative Engineer
    where: Alicante, Spain
    email: jobs@alvaroyuste.com
    gravatar: hola@alvaroyuste.com
    social:
      github: http://github.com/alvyuste
      twitter: http://twitter.com/alvyuste
      facebook: https://www.facebook.com/AlvYuste
      linkedin: https://www.linkedin.com/in/alvaroyuste/
  current:
    - who: Birda
      what: Head of Engineering
      when: Since Sept 2025
      where: London (Remote)
      image: /images/birda.jpg
    - who: Alicante Frontend
      what: Cofounder
      when: Since Oct 2016
      where: Alicante
      image: /images/alicantefrontend.jpg
  experience:
    - who: Open Webinars
      what: Teacher
      when: Since May 2019
      where: Madrid
      image: /images/openwebinars.png
    - who: Spotahome
      what: Senior Engineering Manager
      when: Since March 2019
      where: Madrid
      image: /images/spotahome.png
    - who: SUEZ S.A.
      what: Frontend Architect
      when: Mar 2018 - Mar 2019
      where: Alicante
      image: /images/suez.jpg
    - who: University of Alicante
      what: Teacher
      when: Oct 2014 - Jun 2018
      where: Alicante
      image: /images/ua.jpg
    - who: Nitsnets S.L.
      what: Frontend Engineer
      when: Mar 2016-Mar 2018
      where: Alicante
      image: /images/nitsnets.jpg
    - who: Sonneil S.L.
      what: CTO
      when: Jan 2015-Mar 2016
      where: Alicante
      image: /images/sonneil.jpg
    - who: Iristrace B.V.
      what: Dev & Partner
      when: Jan 2014-Jan 2018
      where: Amsterdam
      image: /images/iristrace.jpg
    - who: Nanonino
      what: Software Dev
      when: Apr 2013-Jan 2014
      where: Alicante
      image: /images/nanonino.jpg
  awards:
    - who: Instant Banking Hack Day
      what: Best IT Development
      when: Feb 2015
      where: Alicante
      image: /images/bancosabadell.jpg
    - who: Imagine Express
      what: Dreammer
      when: Feb 2015
      where: Barcelona, Paris and London
      image: /images/imagine.png
    - who: Fundeun. Nuevas Ideas Empresariales.
      what: Best IT Company
      when: July 2014
      where: Alicante
      image: /images/fundeun.jpg
    - who: Startupbootcamp
      what: Alumni
      when: Since Apr 2014
      where: Amsterdam
      image: /images/sbc.png
  education:
    - who: The Power
      what: The Power MBA
      when: 2021
      where: Online
      image: /images/thepower.png
    - who: University of Alicante
      what: Multimedia Engineering Degree
      when: 2010-2014
      where: Alicante
      image: /images/ua.jpg
    - who: Invattur
      what: IT in Turism
      when: 2013-2014
      where: Benidorm
      image: /images/invattur.jpg
  skills:
    - Data driven prioritizarion, OKRs and experimentation
    - Hiring, career development, training, and crisis management
    - UX focused, Design Thinking and problem solving
    - Distributed software architectures, CQRS, microservices
    - Culture builidng around distributed ownership and autonomy
    - Global vision merging custumer-centric design, business and coding
    - Javascript Fullstack development (Angular/React, Nodejs, Mongo/SQL)
    
