nav:
  Home: /
  About: /about/
  Projects: /projects/
  CV: /cv/

projects_url: http://github.com/alvyuste

customize:
  gravatar:
    email: alvaroyustetorregros@gmail.com
  logo:
    enabled: false
    width: 50
    height: 50
    url: /images/logo.png
    gravatar: true
  favicon:
    # eg. generate with http://realfavicongenerator.net/
    desktop:
      url: /images/favicon.ico
      gravatar: false
    android:
      url: /images/favicon-192x192.png
      gravator: false
    apple:
      url: /images/apple-touch-icon.png
      gravator: false
  social_links:
    github: http://github.com/alvyuste
    twitter: http://twitter.com/alvyuste
    facebook: https://www.facebook.com/AlvYuste
    linkedin: https://www.linkedin.com/in/alvaroyuste/
  show_all_posts: false
  post_count: 5
  highlight: monokai

# RSS
rss: false

# Plugins
plugins:
  disqus_shortname: # Disqus Comments Shortname
  google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
  open_graph: # see http://ogp.me
    fb_app_id:
    fb_admins:
    twitter_id:
    google_plus:
